### ISSUE TITLE
deprecate dev branch

### ISSUE THREAD

**Issue by michaeltryby** [OpenWaterAnalytics/ci-tools#11]
Hey @cbuahin given the scope of what we are doing in this repo I think maintaining a `dev` branch unnecessarily complicates things. I propose making `master` the default branch and deprecating `dev`. Thoughts? 

Happy to consider any concerns or objections you may have.  Thanks!

**Comment by cbuahin** [comment]
@michaeltryby , that sounds entirely reasonable.

**Comment by michaeltryby** [comment]
Settings for repo have been updated. Closing this issue.
