### ISSUE TITLE
GitHub Actions echo ::set-env command has been deprecated

### ISSUE THREAD

**Issue by michaeltryby** [OpenWaterAnalytics/ci-tools#6]
The swmm build is failing. We can no longer postpone fixing this issue.

**Comment by michaeltryby** [comment]
Our scripts use the `echo ::set-env` command to set environment variables so they can be shared between scripts. The issue is that the this command has been deprecated for security reasons. So we need another approach. 

One immediate workaround would be to set the `ACTIONS_ALLOW_UNSECURE_COMMANDS` environment variable to `true`. This would allow us to continue to use our existing scripts with no modification.

**Comment by michaeltryby** [comment]
@cbuahin what is the new approach that Actions uses in place of the `echo ::set-env` command.

**Comment by cbuahin** [comment]
@michaeltryby, according to the documentation this is the new approach to set environment variables.

```
echo "action_state=yellow" >> $GITHUB_ENV
```
https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-commands-for-github-actions#environment-files

**Comment by michaeltryby** [comment]
@cbuahin so the issue is that you haven't been able to get the new syntax to work when called from a script file?

**Comment by cbuahin** [comment]
@michaeltryby, that is correct. I have added this recommended approach to the script and I'm testing it now.

**Comment by cbuahin** [comment]
@michaeltryby, I have fixed linux and darwin but windows is not working out well. I'm not sure what is up.
